accounts/urls.py
from django.urls import path

from accounts import views

app_name="accounts"
urlpatterns = [
    path("login/", views.login, name="login"),
    path("register/", views.register, name="register"),
    path("logout/", views.logout, name="logout"),
    path("profile/", views.profile, name="profile"),
    path("", views.home, name="home")
]

userauth/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms.models import ModelForm


class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email',)


class UserUpdateForm(ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email',)
        exclude = ('password',)

accounts/views.py
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm, UserChangeForm
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse

from accounts.forms import UserForm, UserUpdateForm


# Create your views here.
def login(request):
    # Form has been submitted.
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(request, username=username, password=password)
            if user is not None:
                auth_login(request, user)
                return HttpResponseRedirect(reverse("accounts:home"))
    # If it's a GET request, return an empty form
    else:
        form = AuthenticationForm()

    return render(request, "accounts/login.html", {"form": form})

def register(request):
    # Form has been submitted.
    if request.method == "POST":
        # bind data to form
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("accounts:login"))
    # If it's a GET request, return an empty form
    else:
        form = UserForm()

    return render(request, "accounts/register.html", {"form": form})

def logout(request):
    auth_logout(request)
    return redirect("accounts:login")

@login_required
def home(request):
    return render(request, "accounts/home.html", {})

@login_required
def profile(request):
    if request.method == "POST":
        form = UserUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
    else:
        form = UserUpdateForm(instance=request.user)
    return render(request, "accounts/profile.html", {"form": form})

accounts/templates/accounts/home.html
{% extends "base.html" %}

{% block content %}
	<div class="d-inline d-flex justify-content-between">
        <p>Welcome, {% if request.user.first_name %}{{ request.user.first_name }}{% else %}{{ request.user }}{% endif %}.</p>
        <a href="{% url 'accounts:profile' %}"><p>Profile</p></a>
    </div>

    <form action="{% url 'accounts:logout' %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Logout" class="btn btn-primary">
    </form>


{% endblock %}

accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block title %}
	Login
{% endblock %}

{% block content %}
    <h2 class="pb-4">Log in</h2>
    <div class="d-flex align-items-end justify-content-between">
        <div>
            <form action="{% url 'accounts:login' %}" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Log in" class="btn btn-primary">
            </form>
        </div>
        <a href="{% url 'accounts:register' %}">Register</a>
    </div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends "base.html" %}

{% block content %}
    <div class="d-flex d-inline justify-content-between">
        <h2>Profile</h2>
        <a href="{% url 'accounts:home' %}">Home</a>
    </div>
    <form action="{% url 'accounts:profile' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update" class="btn btn-secondary">
    </form>
{% endblock %}

accounts/templates/accounts/register.html
{% extends "base.html" %}

{% block title %}
	Register
{% endblock %}

{% block content %}
    <h2 class="pb-4">Create an Account</h2>
    <div class="d-flex align-items-end justify-content-between">
        <div class="pt">
            <form action="{% url 'accounts:register' %}" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Register" class="btn btn-primary mt-4">
            </form>
        </div>
        <a href="{% url 'accounts:login' %}">Log in</a>
    </div>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-SgOJa3DmI69IUzQ2PVdRZhwQ+dy64/BUtbMJw1MZ8t5HZApcHrRKUc4W0kG879m7" crossorigin="anonymous">
  </head>
  <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/js/bootstrap.bundle.min.js" integrity="sha384-k6d4wzSIapyDyv1kpU366/PK5hCdSbCRGRCMv+eplOQJWyd1fbcAu9OCUj5zNLiq" crossorigin="anonymous"></script>
    {% if request.user.is_authenticated %}
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <a class="mx-4 navbar-brand" href="#">User Auth</a>
          <button class="mx-4 navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'accounts:home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:profile' %}">Profile</a>
              </li>
            </ul>
          </div>
        </nav>
    {% endif %}
    <div class="container pt-4">
    {% block content %}

    {% endblock %}
    </div>
  </body>
</html>